export const GET_DEVICE_TELEMETRY = "GET_DEVICE_TELEMETRY";
export const TELEMETRY_AVAILABLE = "TELEMETRY_AVAILABLE";
export const SIGN_IN_USER = "SIGN_IN_USER";
export const SIGN_UP_USER = "SIGN_UP_USER";
export const USER_SIGNED_IN = "USER_SIGNED_IN";
